name: CI

on:
  push:
    branches: [ "main" ]
    paths: ["**/.env"]
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_names: ${{ steps.create_tag_push.outputs.tag_names }}
    steps:
      - uses: actions/checkout@v3
      - id: create_tag_push
        name: Create Tag & Push
        run: |
          tag_names=()
          for var in 1 2
          do
            tag_name="$(date +%Y%m%d_%H%M%S)$var"
            git tag $tag_name
            git push origin $tag_name
            tag_names+=("'$tag_name'")
          done
          
          joined_tag_names="$(IFS=,; echo "[${tag_names[*]}]")"
          echo "::set-output name=tag_names::$joined_tag_names"

  create_release:
    needs: create_tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag_name: ${{ fromJson(needs.create_tag.outputs.tag_names) }}
    steps:
      - uses: actions/checkout@v3
      - id: generate_release_note
        name: Generate Release Note
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          previous_tag_name=''
        
          # Generate Release note
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name=${{ matrix.tag_name }} \
            -f previous_tag_name=$previous_tag_name | jq -r '.body' | tr -d '"' > RELEASE_NOTE.md
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ matrix.tag_name }}
          body_path: RELEASE_NOTE.md
          draft: true
