name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Tag & Push
        run: |
          tag_name="$(date +%Y%m%d_%H%M%S)"
          git tag -a $tag_name -m "hoge"
          git push origin $tag_name
