name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: create_tag_push
        name: Create Tag & Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="$(date +%Y%m%d_%H%M%S)"
          git tag $tag_name
          git push origin $tag_name
          
          # Generate Release note
          release_note=`gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name=$tag_name \
            -f previous_tag_name=$previous_tag_name | jq '.body'`
            
          echo $release_note

          # Create draft release
          gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases \
            -f tag_name="$tag_name" \
            -f name="Release $tag_name" \
            -f body="$release_note" \
            -F draft=true
