name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_names: ${{ steps.create_tag_push.outputs.tag_names }}
    steps:
      - uses: actions/checkout@v3
      - id: create_tag_push
        name: Create Tag & Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="$(date +%Y%m%d_%H%M%S)"
          git tag $tag_name
          git push origin $tag_name
          
          tag_names="[$tag_name]"
          echo "::set-output name=tag_names::$tag_names"

  create_release:
    needs: create_tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag_name: ${{ fromJson(needs.create_tag.outputs.tag_names) }}
    steps:
      - id: generate_release_note
        name: Generate Release Note
        run: |
          previous_tag_name=''
        
          # Generate Release note
          release_note=`gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name=${{ matrix.tag_name }} \
            -f previous_tag_name=$previous_tag_name | jq '.body'`
            
          echo "::set-output name=release_note::$release_note"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ matrix.tag_name }}
          body: ${{ steps.generate_release_note.outputs.release_note }}
          draft: true
